FROM python:3.8.2-alpine

# set work directory
WORKDIR /usr/src/app

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# install dependencies
RUN apk update \
    && apk add postgresql-dev gcc python3-dev musl-dev uwsgi-python3 build-base linux-headers pcre-dev

# install dependencies
RUN pip install --upgrade pip
COPY ./chika/requirements.txt /usr/src/app/requirements.txt
RUN pip install -r requirements.txt
