version: '3.7'

services:
  web:
    build:
      context: ./
      dockerfile: ./Dockerfile.dev.chika
    volumes:
      - ./chika:/usr/src/app/
    ports:
      - 8080:8080
      - 8081:8081
      - 9000:9000
    env_file:
      - ./.env
    depends_on:
      - db
      - rabbitmq
    command: python ./manage.py runserver 0.0.0.0:${PORT}
  db:
    image: postgres:${PG_VERSION}
    ports:
      - 5432:5432
    volumes:
      - ./db/src:/docker-entrypoint-initdb.d
    env_file:
      - ./.env
    environment:
      # env vars specific to postgres image used on first boot
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      # env vars useful for sql scripts
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DEVELOPMENT=${DEVELOPMENT}
  pg_amqp_bridge:
    image: subzerocloud/pg-amqp-bridge
    env_file:
      - ./.env
    environment:
      - RUST_LOG=info
      - POSTGRESQL_URI=postgres://${DB_USER}:${DB_PASS}@${DB_HOST}:5432/${DB_NAME}
      - AMQP_URI=amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@${RABBITMQ_HOST}//
      - BRIDGE_CHANNELS=chat:amq.fanout
    depends_on:
      - db
      - rabbitmq
  rabbitmq:
    build: 
      context: ./
      dockerfile: ./Dockerfile.dev.rabbitmq
    ports:
      - 5671:5671
      - 5672:5672
      - 15670:15670
      - 15672:15672
      - 15674:15674
    env_file:
      - ./.env
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}

volumes:
  postgres_data: